version: '3'
services:
  web:
    build: .
    links:
      - api
      - websocket
    depends_on:
      - api
      - websocket
    ports:
      - "9000:9000"
      - "9001:9001"
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports: 
      - "8089:8089" # creo que se deberia quitar y seguir funcionando correctamente pues accedo por 9000
    command: python api.py
    stdin_open: true
    tty: true
  websocket:
    build:
      context: .
      dockerfile: Dockerfile-websocket
    #ports: 
    command: python websocket-s.py
    stdin_open: true
    tty: true
